project_structure:
    build: build
    contracts: src/l1
    interfaces: src/l1/interfaces
    reports: reports
    scripts: scripts
    tests: tests/l1

dotenv: .env

compiler:
  solc:
    version: 0.8.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2

console:
  show_colors: false
